package SendFileServer;


/**
* SendFileServer/SendFile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SendFileServer.idl
* miércoles 10 de octubre de 2018 11:20:25 AM CDT
*/

public interface SendFile extends SendFileOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SendFile
