package SendFileServer;

/**
* SendFileServer/SendFileHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SendFileServer.idl
* miércoles 10 de octubre de 2018 11:20:25 AM CDT
*/

public final class SendFileHolder implements org.omg.CORBA.portable.Streamable
{
  public SendFileServer.SendFile value = null;

  public SendFileHolder ()
  {
  }

  public SendFileHolder (SendFileServer.SendFile initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SendFileServer.SendFileHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SendFileServer.SendFileHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SendFileServer.SendFileHelper.type ();
  }

}
