package SendFileServer;


/**
* SendFileServer/SendFileHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SendFileServer.idl
* miércoles 10 de octubre de 2018 11:20:25 AM CDT
*/

abstract public class SendFileHelper
{
  private static String  _id = "IDL:SendFileServer/SendFile:1.0";

  public static void insert (org.omg.CORBA.Any a, SendFileServer.SendFile that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SendFileServer.SendFile extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SendFileServer.SendFileHelper.id (), "SendFile");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SendFileServer.SendFile read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SendFileStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SendFileServer.SendFile value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SendFileServer.SendFile narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SendFileServer.SendFile)
      return (SendFileServer.SendFile)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SendFileServer._SendFileStub stub = new SendFileServer._SendFileStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SendFileServer.SendFile unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SendFileServer.SendFile)
      return (SendFileServer.SendFile)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SendFileServer._SendFileStub stub = new SendFileServer._SendFileStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
